export const config = {
  name: "Secure API Demo",
  tag: "TRUST LAB",
  description: "La identidad se verifica. El acceso también.",
  post: "/api/me",
  list: "/api/me",
  sample: {},
  columns: ["subject", "roles", "issuer"],
  concepts: ["OAuth 2.0 / JWT", "Roles + propiedad", "TLS / mTLS"],
  scenarios: [],
  repo: "secure-api-demo",
  index: 5,
  secure: true,
  payment: false,
  monitor: false,
  brand: "umbral",
  label: "CONFIANZA, CON CONDICIONES",
  title: "La puerta correcta.",
  emphasis: "Para cada identidad.",
  intro:
    "Comprueba quién eres, qué puedes consultar y por qué. Un espacio para explorar permisos y acceso seguro a una API.",
  accent: "#859be8",
  soft: "#f0f2f8",
  kind: "secure",
  form: "Comprueba tu acceso",
  button: "Consultar recurso",
  steps: ["Obtén una identidad", "Elige el recurso", "Comprueba el permiso"],
  features: [
    [
      "01",
      "Identidad verificada",
      "La API valida la firma y vigencia del token.",
    ],
    [
      "02",
      "Permisos concretos",
      "Lectores y administradores acceden a recursos distintos.",
    ],
    [
      "03",
      "Lo tuyo es tuyo",
      "Una identidad válida no da acceso a cuentas de otros.",
    ],
  ],
};
